spring:
  graphql:
    graphiql.enabled: true
    schema.printer.enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase?createDatabaseIfNotExist=true&useSSL=false
    username: admin
    password: secret